In [4]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
df=pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score,precision_score
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
X=df.iloc[:,:8]
y=df.iloc[:,8]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)
print(precision_score(y_test,y_pred))
#plt.figure(figsize=(4,4),dpi=800)
#plot_tree(classifier)

Confusion Matrix:
[[115  38]
 [ 35  43]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.75      0.76       153
           1       0.53      0.55      0.54        78

    accuracy                           0.68       231
   macro avg       0.65      0.65      0.65       231
weighted avg       0.69      0.68      0.69       231

Accuracy: 0.683982683982684
0.5308641975308642


In [6]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)
print(precision_score(y_test,y_pred))

Confusion Matrix:
[[131  22]
 [ 31  47]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.86      0.83       153
           1       0.68      0.60      0.64        78

    accuracy                           0.77       231
   macro avg       0.74      0.73      0.74       231
weighted avg       0.77      0.77      0.77       231

Accuracy: 0.7705627705627706
0.6811594202898551


In [10]:
from sklearn.ensemble import GradientBoostingClassifier
gradient_booster = GradientBoostingClassifier(learning_rate=0.1)
gradient_booster.fit(X_train,y_train)
y_pred = gradient_booster.predict(X_test)
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)
print(precision_score(y_test,y_pred))

Confusion Matrix:
[[129  24]
 [ 31  47]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       153
           1       0.66      0.60      0.63        78

    accuracy                           0.76       231
   macro avg       0.73      0.72      0.73       231
weighted avg       0.76      0.76      0.76       231

Accuracy: 0.7619047619047619
0.6619718309859155


In [11]:
params={'learning_rate':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]}
gsearch=GridSearchCV(gradient_booster,params, verbose=1, cv=3)
gsearch.fit(X_train, y_train)
print(gsearch.best_params_)

NameError: name 'GridSearchCV' is not defined